specVersion: 0.0.1
description: "A proof of concept for fetching web2 data from a subquery deployment"
repository: git@github.com:talismansociety/subquery-fetch-poc.git
schema: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7500000
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
